### ISSUE TITLE
how i can use it in fragment?

### ISSUE THREAD

**Issue by SamgarN** [UdiOshi85/libSearchToolbar#1]
I am a beginner .  i am try to use it in fragment. help me how can do it ?

**Comment by UdiOshi85** [comment]
Hi SamgarN,
The best approach to handle toolbar and it's clicks it's in activity, of course it can be handle also from nested views/fragment but I would suggest you to manage your Toolbar in an activity and notify the fragment for any actions.

Nevertheless, I'll check this issue with fragments and see if it's possible and what are the consequences.
Don't forget to Star us if you like the code :)

**Comment by UdiOshi85** [comment]
Hi SamgarN,

After doing some reading and checking all the possible options, it is recommended to handle your Toolbar from activity. Of course it is possible to do it in inside the fragment but since the Activity is the owner of the mechanism I would recommend to put it inside there and not in your fragments. Good luck!

**Comment by UdiOshi85** [comment]
Hi SamgarN,

After reading more, i'll publish new version in the next days (The version will be 1.1.0)
It will support using in fragment (i'll provide an example)
Once i'll finish i will close this issue.

**Comment by UdiOshi85** [comment]
Hi SamgarN,

I've released 1.1.0 version which includes supporting inside fragment.
You can see how in the example application: https://github.com/UdiOshi85/SearchToolbarExample
I've update https://github.com/UdiOshi85/libSearchToolbar readme page as well.

Good luck!

Udi
