### ISSUE TITLE
Set Toolbar Query programatically at Activity create.

### ISSUE THREAD

**Issue by ThrownFran** [UdiOshi85/libSearchToolbar#2]
Hi again UdiOshi85!

Very happy with your library, I have some needs in my App I dont know how to do with your Library.

1. When starting activity, I would like to set a Query in the Search Toolbar that was sent from intent.
2. When I press Submit, how can I unfocus the Toolbar EditText? (Not so important)

Thank you!! 👍

**Comment by UdiOshi85** [comment]
Hi,
1. I will update the library with setQuery function (Please note that some listeners will be called due to onQueryTextChange).

2. I wouldn't recommend messing with the native focus, let the system handle all focuses/keyboard by itself.

3. The update is scheduled for tomorrow (About ~18 hours from now) so if you wish for more features don't hesitate to open another issues.

Udi

**Comment by UdiOshi85** [comment]
Hi ThrownFran,

Library updated!
compile 'com.github.udioshi85:libSearchToolbar:1.2.**1**'

I've added a new public function named
public void expandAndSearch(String query)

Notes:
This function expands the toolbar (**Without animation**) and updates the search text area with the given query.
Once this function has been called, the library will also notify for onSearchQueryChanged.

Enjoy.
